# Workflow of actions to verify dxapp.json

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify_json:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Set contents of dxapp.json to env variable to access in following steps
      - name: Set env
        run: echo "DXAPP_JSON=$(jq -c < dxapp.json)" >> $GITHUB_ENV       
        
      - name: Verify eggd prefix in name
        if: always()
        run: |
          name=$(jq -r '.name' <<< $DXAPP_JSON)
          if [[ "$name" != eggd_* ]]; then echo "Missing eggd_ prefix from name"; exit 1; fi
      
      - name: Verify eggd prefix in title
        if: always()
        run: |
          if [[ $(jq -r '.title' <<< $DXAPP_JSON) != eggd_* ]]; then echo "Missing eggd_ prefix from title"; exit 1; fi
        
      - name: Verify version set
        if: always()
        run: |
          if [[ $(jq -r '.version' <<< $DXAPP_JSON) == null ]]; then echo "Missing version field"; exit 1; fi
      
      - name: Verify timeoutPolicy set
        if: always()
        run: |
          if [[ $(jq -r '.runSpec.timeoutPolicy' <<< $DXAPP_JSON) == null ]]; then echo "Missing timeout policy"; exit 1; fi
      
      - name: Verify developers set to org-emee_1
        if: always()
        run: |
          if [[ $(jq -r '.developers[]' <<< $DXAPP_JSON) == 'org-emee_1' ]]; then echo "Developers not set to org-emee_1"; exit 1; fi
      
      - name: Verify authorizedUsers set to org-emee_1
        if: always()
        run: |
          if [[ $(jq -r '.authorizedUsers[]' <<< $DXAPP_JSON) == 'org-emee_1' ]]; then echo "Authorised users not set to org-emee_1 "; exit 1; fi
          
#       - name: 
#         if: always()
#         run: |
#           if [[ $(jq -r '.' <<< $DXAPP_JSON) == null ]]; then echo "Missing "; exit 1; fi
          
          
          
          
          
          
#         - name: 
#         if: always()
#         run: |
#           if [[ $(jq -r '.' <<< $DXAPP_JSON) == null ]]; then echo "Missing "; exit 1; fi
  
  
  
  
  
  
  
  
  
  
  
  
